### ISSUE TITLE
Documentation url 404

### ISSUE THREAD

**Issue by progtologist** [ros-controls/joss_paper#22]
The README.md of most (if not all) repos in ros_control is pointing to http://ros.org/wiki/ros_control while it should be pointing to http://wiki.ros.org/ros_control

**Comment by bmagyar** [comment]
I have updated the readme file of all _released_ repositories. All include the wiki link both to `ros_control` and their respective wiki pages except for `control_msgs` where knowing and using `ros_control` is not required to be [using the messages](https://github.com/fetchrobotics/robot_controllers)

**Comment by mathias-luedtke** [comment]
I am not sure if this is actually a bug with `ros.org`, which lacks the redirect rule.

**Comment by bmagyar** [comment]
They used to have it, I guess it got retired.

**Comment by bmagyar** [comment]
Resolved
