### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by progtologist** [ros-controls/joss_paper#23]
JOSS requires a LICENSE file to be provided in the repository. Strictly speaking this is not the case with ros_control, though the license is clearly stated inside each source file. 

I am not sure whether this should be "fixed" or be considered redundant.

**Comment by bmagyar** [comment]
We also specify the license at the package level in each `package.xml`. 

It is probably best to refer to the editors.

**Comment by danielskatz** [comment]
JOSS requires a ```LICENSE``` or ```LICENSE.txt``` file in the root of the repository.

**Comment by bmagyar** [comment]
Done: 
https://github.com/ros-controls/ros_control/commit/d8a2c5e805a22b6f53c48789bc5dd47692e47772
